init_env: "{{ init_env_common|combine(init_env_stg) }}"

domains: "stg-learn.knightlab.com"
service_exec: "{{ virtualenv}}/bin/gunicorn -b :{{ service_port }} --workers 1 --reload {{ wsgi_application }}"

init_env_stg:
  URL_ROOT: "https://learncms.knightlab.com"
  AWS_STORAGE_BUCKET_NAME: "media.knilab.com"

init_env: "{{ init_env_common|combine(init_env_prd) }}"

