domain: "{{ project_name }}.knilab.com"
staticbucket: "media.knilab.com/{{ project_name }}"
gunicorn_reload: True # generally True on staging only
ssl:
  ssl_certificate: /etc/nginx/ssl/knilab/knilab-bundle.crt
  ssl_certificate_key: /etc/nginx/ssl/knilab/knilab-com.key
