project_name: learncms
gitdeploy_version: "1.0.5"
port: 9018
python: python3
type: django # (django|flask|other|repository)

nginx_conf: "{{ deploy_dir }}/nginx/conf.d/{{ project_name }}.conf"

# these will be merged with deployment-specific env into init_env
init_env_common:
  PROJECT_NAME: "{{ project_name }}"
  APPLICATION_DOMAINS: "{{ domains }}" # space-delimited
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  STATIC_TMPDIR: "{{ static_dir }}"
  DJANGO_SECRET_KEY: "{{ vault_django_secret_key }}"
  DB_ENGINE__DEFAULT: "django.db.backends.postgresql_psycopg2"
  DB_NAME__DEFAULT: "{{ project_name }}_{{ env }}"
  DB_USER__DEFAULT: "{{ vault_db_user__default }}"
  DB_PASSWORD__DEFAULT: "{{ vault_db_password__default }}"
  DB_HOST__DEFAULT: "{{ vault_db_host__default }}"
  DB_PORT__DEFAULT: "{{ vault_db_port__default }}"


# Django specific configs
django_settings_module: "core.settings.ec2"
static_dir: "/tmp/{{ project_name }}_static"
static_prep: ". /home/apps/env/learncms/bin/activate; /home/apps/.local/bin/runenv manage.py collectstatic --noinput"
#static_prep: "{{ env_run_script }} manage.py collectstatic --noinput"
#env_run_script: "{{ deploy_dir }}/env_run.sh"


# Configs below will not usually change
deploy_dir: "{{ install_root }}/{{ project_name }}"
env_file: "{{ deploy_dir }}/.env"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
application_dir: "{{ deploy_dir }}" # application dir could be a subdirectory
requirements_file: "{{ deploy_dir }}/requirements.txt"
virtualenv: "{{ virtualenv_root }}/{{ project_name }}"
wsgi_application: "core.wsgi:application"
service_name: "{{ project_name }}"
static_service: "s3"
static_dest: "s3://{{ static_bucket }}/{{ project_name }}"

# Configs common to all projects
application_user: apps
install_root: /home/{{ application_user }}/sites
virtualenv_root: /home/{{ application_user }}/env

# environment keys must match deployment branch names. Value is the name
# of the branch to be merged into this environment during deployment.
supported_envs:
  stg: master
  prd: stg
