project_name: learncms
service_name: "{{ project_name|lower }}"
gitdeploy_version: "1.0.6"
python_version: "3.7.17"
python: /home/apps/sites/twxplorer/.venv/bin/python
service_port: "{{ learncms_port }}"
nginx_template: learncms.conf

playbooks:
  - playbook.deploy-repo.yml
  - playbook.deploy-web.yml
  - playbook.restart.yml

# these will be merged with deployment-specific env into init_env
init_env_common:
  PROJECT_NAME: "{{ project_name }}"
  APPLICATION_DOMAINS: "{{ domains }}" # space-delimited
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  # STATIC_TMPDIR: "{{ static_dir }}"
  DJANGO_SECRET_KEY: "{{ vault_django_secret_key }}"
  DB_ENGINE__DEFAULT: "django.db.backends.postgresql_psycopg2"
  DB_NAME__DEFAULT: "{{ project_name }}_{{ env }}"
  DB_USER__DEFAULT: "{{ vault_db_user__default }}"
  DB_PASSWORD__DEFAULT: "{{ vault_db_password__default }}"
  DB_HOST__DEFAULT: "{{ vault_db_host__default }}"
  DB_PORT__DEFAULT: "{{ vault_db_port__default }}"


# Django specific configs
django_settings_module: "core.settings.ec2"

#static_dir: "/tmp/{{ project_name }}_static"
#env_run_script: ". {{ virtualenv }}/bin/activate; /home/apps/.local/bin/runenv .env"
#env_run_script: "direnv exec {{ deploy_dir }}"
#static_prep: "{{ env_run_script }} ./manage.py collectstatic --noinput"
#static_prep: "{{ env_run_script }} manage.py collectstatic --noinput"
#env_run_script: "{{ deploy_dir }}/env_run.sh"


install_root: "/home/apps/sites"
deploy_dir: "{{ install_root }}/{{ project_name }}"
application_dir: "{{ deploy_dir }}"
env_file: "{{ deploy_dir }}/.env"
envrc_file: "{{ deploy_dir }}/.envrc"
virtualenv: "{{ deploy_dir }}/.venv"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
requirements_file: "{{ deploy_dir }}/requirements.txt"
wsgi_application: "core.wsgi:application"
static_root: "{{ application_dir }}/static"
