domain: "learn.knightlab.com"
staticbucket: "media.knightlab.com/{{ project_name }}"
gunicorn_reload: False
ssl:
  ssl_certificate: /etc/nginx/ssl/knightlab/knightlab-bundle.crt
  ssl_certificate_key: /etc/nginx/ssl/knightlab/knightlab-com.key
